### ISSUE TITLE
Do not start Contact Mechanics analysis for line scans

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/topobank-contact#1]
It would be cleaner not to create the contact analysis for line scans at all, because they must always fail.
In general this could be implemented by providing a test function for each analysis function, which checks whether
the function can be applied to a subject or not.

**Comment by pastewka** [comment]
This actually seems overly complicated to me. I would just let those runs fail. We may actually implement contact mechanics for 1D systems at some point, although I am not sure how useful this would be in the context of measurements.
